apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: projetdevsecops
    version: "1.0"
  name: projetdevsecops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: projetdevsecops
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: projetdevsecops
    spec:
      containers:
        - name: projetdevsecops
          image: nathanremond/projetdevsecops:1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: projetdevsecops
  name: projetdevsecops
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
      name: http
  selector:
    app: projetdevsecops
  type: LoadBalancer
status:
  loadBalancer: {}
